apiVersion: v1
kind: Secret
metadata:
  name: echo-api-db-secret
  namespace: echo-app-ns
data:
  dbpass: UEBzc3cwcmQ=
  connString: VXNlciBJRD1kYnVzZXI7UGFzc3dvcmQ9UEBzc3cwcmQ7U2VydmVyPWVjaG8tZGItc3RzLTAuZWNoby1kYi1zdHMtc3ZjLmVjaG8tYXBwLW5zLnN2Yy5jbHVzdGVyLmxvY2FsO1BvcnQ9NTQzMjtEYXRhYmFzZT1FY2hvRGI7SW50ZWdyYXRlZCBTZWN1cml0eT10cnVlO1Bvb2xpbmc9dHJ1ZTsK
