apiVersion: v1
kind: PersistentVolume
metadata:
  name: sample-pv
  labels:
    type: sample-storage
spec:
  capacity:
    storage: 5Mi
  volumeMode: Filesystem
  storageClassName: microk8s-hostpath-retain
  accessModes:
  - ReadWriteOnce
  local:
    path: /tmp/microk8s-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - tiberna-rasp-003