apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-pv-claim-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 1Mi