apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-pvc
  template:
    metadata:
      labels:
        app: redis-pvc
    spec:
      nodeSelector:
        kubernetes.io/hostname: tiberna-rasp-003
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 80       
        volumeMounts:
        - mountPath: "/storage/static"
          name: static-storage
        - mountPath: "/storage/dynamic"
          name: dynamic-storage
        - mountPath: "/storage/retain"
          name: retain-storage
      volumes:
        - name: static-storage
          persistentVolumeClaim:
            claimName: sample-pv-claim-static
        - name: dynamic-storage
          persistentVolumeClaim:
            claimName: sample-pv-claim-dynamic
        - name: retain-storage
          persistentVolumeClaim:
            claimName: sample-pv-claim-retain
  