apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: rbac-ns
  name: deployments-admin-tiago
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployments-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: dev01