apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rbac-ns
  name: config-db-edit
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["db-config"]
  verbs: ["get", "list", "update"]
