apiVersion: v1
kind: Namespace
metadata:
  name: rbac-ns

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rbac-ns
  name: deployments-admin
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]