apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
  annotation:
    kubernetes.io/change-cause: "changed to marron"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: workload-1
  template:
    metadata:
      labels:
        app: workload-1
        color: pink
    spec:
      containers:
        - name: workload
          image: nginx:1.17
          ports:
            - containerPort: 80
