
replicaCount: 1

image:
  repository: tasb/echo-webapp
  tag: "k8s-v2"

service:
  type: ClusterIP
  port: 80

echoAPIURL: echo-api-svc:8080

ingress:
  enabled: false
  className: ""
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  host: echo-app.ingress.test
      
  paths:
  - path: /(.*)
    pathType: Prefix


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilization: 250m
  # targetMemoryUtilization: 500Mi
