apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodename-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
        run: nodename
  template:
    metadata:
      labels:
        run: nodename
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP
      nodeName: tiberna-hp