apiVersion: apps/v1
kind: Deployment
metadata:
  name: taint-equals
spec:
  replicas: 2
  selector:
    matchLabels:
        run: nodename
  template:
    metadata:
      labels:
        run: nodename
    spec:
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - arm64
      containers:
      - name: web
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP
      tolerations:
      - key: "PriorityLevel"
        operator: "Equal"
        value: "Critical"
        effect: "NoSchedule"