
apiVersion: v1
kind: Service
metadata:
  name: {{ include "echo-app-web.fullname" . }}-svc
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      name: web
  selector:
    app: echo-app
    tier: front
  type: {{ .Values.service.type }}
