apiVersion: apps/v1
kind: Deployment
metadata:
  name: probes-demo
spec:
  selector:
    matchLabels:
      run: probes-demo
  replicas: 1
  template:
    metadata:
      labels:
        run: probes-demo
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64 
      containers:
      - name: probes-demo
        image: ghcr.io/theonorg/swissknife-api:1.6
        ports:
        - name: http-port
          containerPort: 80
        resources:
          limits:
            cpu: 300m
          requests:
            cpu: 100m
        startupProbe:
          httpGet:
            path: /healthz/start
            port: http-port
          periodSeconds: 20
          timeoutSeconds: 20
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 80
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 15
          periodSeconds: 2
          timeoutSeconds: 5
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 80
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 15
          periodSeconds: 2
          failureThreshold: 3
          timeoutSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: probes-demo-svc
spec:
  ports:
    - port: 10000
      targetPort: 80
      name: web
  selector:
    run: probes-demo
  type: LoadBalancer


