apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: ns-labels
  labels:
    app: myapp
    tier: front
spec:
  containers:
  - image: nginx
    name: nginx-container
    ports:
    - containerPort: 80
