version: '3'
services:
  echo-db:
    image: postgres:14.2-alpine
  
  echo-webapp:
    image: ghcr.io/theonorg/echo-webapp:arm
    build:
      context: echo-webapp
    depends_on:
      - echo-api
  
  echo-api:
    image: ghcr.io/theonorg/echo-webapi:arm
    build:
      context: echo-api
      dockerfile: ./Dockerfile.multi
    depends_on:
      - echo-db