apiVersion: v1
kind: Service
metadata:
  name: {{ include "echo-app-db.fullname" . }}-svc
spec:
  ports:
    - port: 1433
      targetPort: 1433
      name: db
  selector:
    app: echo-app
    tier: db
  clusterIP: None