apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
        run: my-app
  template:
    metadata:
      name: myapp
      labels:
        run: my-app
        tier: frontend
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64 
      containers:
      - name: web
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  labels:
    run: my-app
spec:
  ports:
    - port: 10100
      targetPort: 80
      name: web
  selector:
    run: my-app
    tier: frontend
  type: ClusterIP