version: '3'
services:
  voting-db:
    image: ghcr.io/theonorg/vote-app:redis-arm
  
  voting-app:
    image: ghcr.io/theonorg/vote-app:python-redis-arm
    build:
      context: .
    depends_on:
      - voting-db