apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterinfo-crb
subjects:
 - kind: ServiceAccount
   name: clusterinfo-sa
   namespace: clusterinfo
roleRef:
   kind: ClusterRole
   name: clusterinfo-cr
   apiGroup: rbac.authorization.k8s.io