apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterinfo-cr
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources:
      [
        "containers",
        "logs",
        "endpoints",
        "services",
        "events",
        "limitranges",
        "nodes",
        "namespaces",
        "resourcequotas",
        "limitranges"
      ]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      [
        "secrets",
        "configmaps",
        "persistentvolumeclaims",
        "persistentvolumes",
        "volumes",
      ]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec", "pods/log"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings","clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "watch"]
  # KEDA      
  - apiGroups: ["keda.sh"]
    resources: ["scaledobjects", "scaledjobs"]
    verbs: ["get", "list", "watch"]
  # Key vault Secrets  
  - apiGroups: ["secrets-store.csi.x-k8s.io"]
    resources: ["secretproviderclasses", "secretproviderclasspodstatuses"]
    verbs: ["get", "list", "watch"]
  # Choas Mesh  
  - apiGroups: ["chaos-mesh.org"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  # Open Service Mesh
  - apiGroups: ["config.openservicemesh.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["policy.openservicemesh.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["split.smi-spec.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]    
