// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using echo_api.Models;

#nullable disable

namespace echo_api.Migrations
{
    [DbContext(typeof(EchoHistoryDb))]
    partial class EchoHistoryDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("echo_api.Models.EchoHistory", b =>
                {
                    b.Property<int>("EchoHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EchoHistoryId"));

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.HasKey("EchoHistoryId");

                    b.ToTable("EchoLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
