apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
spec:
  selector:
    matchLabels:
      run: load-generator
  replicas: 1
  template:
    metadata:
      labels:
        run: load-generator
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: load-generator
        image: ghcr.io/theonorg/load-generator:busybox
        imagePullPolicy: Always
        env:
          - name: URL_TEST
            value: 'http://hpa-dotnet-svc:8080/load'