apiVersion: v1
kind: Secret
metadata:
  name: {{ include "echo-app-api.fullname" . }}-secret
data:
  connString: {{ "Server={{ .Values.dbHost }},1433;Initial Catalog=echo-log;User ID={{ .Values.dbUser }};Password={{ .Values.dbPass }}" | b64enc }}
