
apiVersion: v1
kind: Service
metadata:
  name: {{ include "echo-app-api.fullname" . }}-svc
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      name: api
  selector:
    app: echo-app
    tier: back
  type: ClusterIP